name: Generate ZIP file

on:
  workflow_dispatch:
  workflow_call:

jobs:
    generate-zip-file:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Set PHP version
              uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2.32.0
              with:
                php-version: 7.4
                tools: composer:v2

            - name: Install and build
              run: |
                  composer install --no-dev -o
                  composer archive --format=zip --file=bookings-helper
                  rm -rf ./bookings-helper && unzip bookings-helper.zip -d ./bookings-helper

            - name: Use the Upload Artifact GitHub Action
              uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
              with:
                  name: bookings-helper
                  path: bookings-helper/
